import {useState} from "react";
import {
  Box,
  Typography,
  Button,
  TextField,
  Chip,
  IconButton,
  Paper
} from "@mui/material";
import {DataGrid, type GridColDef,} from "@mui/x-data-grid";
import {Download, Trash2, RefreshCw} from "lucide-react";

type ReportStatus = "Completed" | "Processing" | "Failed";

interface ReportHistory {
  id: number;
  reportName: string;
  type: string;
  generatedBy: string;
  generatedAt: string;
  status: ReportStatus;
}

const mockReports: ReportHistory[] = [
  {
    id: 1,
    reportName: "Weekly Performance Report",
    type: "Campaign",
    generatedBy: "Admin",
    generatedAt: "2026-03-05 10:20",
    status: "Completed"
  },
  {
    id: 2,
    reportName: "Monthly Revenue Summary",
    type: "Finance",
    generatedBy: "Analytics Team",
    generatedAt: "2026-03-03 14:10",
    status: "Processing"
  },
  {
    id: 3,
    reportName: "Inventory Fill Rate",
    type: "Inventory",
    generatedBy: "System",
    generatedAt: "2026-03-01 08:45",
    status: "Failed"
  }
];

const statusColor: Record<
  ReportStatus,
  "success" | "warning" | "error"
> = {
  Completed: "success",
  Processing: "warning",
  Failed: "error"
};

export default function ReportsHistoryPage() {
  const [search, setSearch] = useState("");

  const columns: GridColDef<ReportHistory>[] = [
    {field: "reportName", headerName: "Report Name", flex: 1.5},

    {field: "type", headerName: "Type", flex: 0.8},

    {field: "generatedBy", headerName: "Generated By", flex: 1},

    {field: "generatedAt", headerName: "Generated At", flex: 1},

    {
      field: "status",
      headerName: "Status",
      flex: 0.8,
      renderCell: (params) => (
        <Chip
          label={params.value}
          color={statusColor[params.value as ReportStatus]}
          size="small"
        />
      )
    },

    {
      field: "actions",
      headerName: "Actions",
      sortable: false,
      flex: 1,
      renderCell: (params) => (
        <>
          {params.row.status === "Completed" && (
            <IconButton size="small">
              <Download size={18}/>
            </IconButton>
          )}

          {params.row.status === "Failed" && (
            <IconButton size="small">
              <RefreshCw size={18}/>
            </IconButton>
          )}

          <IconButton size="small" color="error">
            <Trash2 size={18}/>
          </IconButton>
        </>
      )
    }
  ];

  const filteredReports = mockReports.filter((report) =>
    report.reportName.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <Box p={3}>
      {/* Header */}
      <Box
        display="flex"
        justifyContent="space-between"
        alignItems="center"
        mb={3}
      >
        <Typography variant="h5" fontWeight="bold">
          Report History
        </Typography>

        <Button variant="contained">
          Generate Report
        </Button>
      </Box>

      {/* Search */}
      <Box mb={2}>
        <TextField
          size="small"
          placeholder="Search reports..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </Box>

      {/* Table */}
      <Paper>
        <DataGrid
          rows={filteredReports}
          columns={columns}
          autoHeight
          pageSizeOptions={[5, 10, 25]}
          disableRowSelectionOnClick
        />
      </Paper>
    </Box>
  );
}